### ISSUE TITLE
Problems using the prebuilt release

### ISSUE THREAD

**Issue by guvenma** [buffer51/android-gfortran#10]
Hello,

Thanks for the great work. 

I downloaded your prebuilt release (linux86_64) and replaced the original NDK toolchain directory with yours.  But I am having problems with using ndk-build recognize the .f90 extension.  It throws a warning "ANDROID NDK: WARNING: Unsupported source file extension in Android.mk".  Is there a specific set up which would make ndk-build aware of gfortran compiler and associate it with f90 extension.

Thanks

**Comment by buffer51** [comment]
Hi @guvenma,

It's been a long time, but if I remember correctly: when I talked about using `ndk-build`, I've never actually used it to build Fortran files directly with an `Android.mk`.

What I've done is:
- a) build libraries that have Fortran code myself (regular Makefiles with the provided toolchain), and produced a shared library (`.so`).
- b) then, setup a Android NDK project that uses those libraries (which you can build with `ndk-build`, perfectly supported).

The toolchain provided is still needed for both step a (to build the Fortran code) and b (so that Android NDK knows where are the Fortran includes & standard libraries), which I why I explain how to replace the toolchain.

There is no interface for you to call your Fortran code from an Android app in Java anyway. So I would suggest build your Fortran code as a library, then creating a C wrapper that uses that library.

Alternatively if you just want to build an executable and run it on your Android device, you should just build your Fortran code with the toolchain (you can use Makefiles, or whatever you fancy) as you would with any regular `gcc`.

**Comment by guvenma** [comment]
I think I understand. I believe I was forcing myself to use ndk-build with [Android.mk + f90 code] hoping that all compiler options suitable for target platforms (as well as the common ones) are set up properly. However, I believe I can manage to do it as you suggest through a C wrapper that uses that library..  Thanks again..
