### ISSUE TITLE
Building x86 toolchain

### ISSUE THREAD

**Issue by bubiche** [buffer51/android-gfortran#2]
Hi,
I followed your guide and I can make the toolchain for armeabi and mips but when I I do `./build --toolchain x86` I got the following error: http://paste.ubuntu.com/16861425/ Can you help me with it please.

My setup:
- Ubuntu 16.04 64bit
- gcc 4.8.5 (newer versions seems to cause errors)
- g++ 4.8.5

Thank you very much!

**Comment by buffer51** [comment]
Hi @bubiche,

I had the same error when I tried. I found a quickfix which allowed me to build successfully ([download here](https://www.dropbox.com/s/0lze5oehxuimikk/gcc-x86-linux-x86_64.tar.bz2?dl=0)), however I am not sure it's ideal.

Could you check if the resulting toolchain works for you? If so I'll update the steps to include the x86 case.

I filled a bug on the [GNU GCC Bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71363), I'm hoping they'll answer even though it's Google's GCC. I've never had luck in getting support from Google, since they don't include Fortran to the NDK.

**Comment by bubiche** [comment]
Thank you mate.

I tried using your toolchain to build OpenBLAS with `make TARGET=ATOM HOSTCC=gcc CC=i686-linux-android-gcc FC=i686-linux-android-gfortran` but it doesn't work, I keep getting the error http://paste.ubuntu.com/16884681/ although I checked in the folder and there is a file called sblat there. Am I doing something wrong?

**Comment by buffer51** [comment]
Can you post your Makefile.conf? It should have the CROSS flag set, but apparently it's not. When it is, it doesn't try to run test because they won't run on your machine (which is what happens here).

Anyway this is an OpenBLAS problem, and the libraries are built fine. To check that, add `libs` to your build command, the error should disappear. After that you can do `make PREFIX=/path/to/install install` to create an install directory.

**Comment by bubiche** [comment]
Yeah, everything works fine now. I tried some other libraries and your toolchain totally works. Thank you very much.

**Comment by buffer51** [comment]
Awesome :) I will commit the temporary steps, awaiting an answer from the GNU guys.

**Comment by buffer51** [comment]
I pushed the steps, as GNU support said it's a won't fix.

**Comment by mhsmith** [comment]
In case the pastebin goes away, here's the original error:

```
/toolchain/build/../gcc/gcc-4.9/libgfortran/intrinsics/cshift0.c: In function 'cshift0':
/toolchain/build/../gcc/gcc-4.9/libgfortran/intrinsics/cshift0.c:150:5: error: duplicate case value
     case GFC_DTYPE_REAL_16:
     ^
/toolchain/build/../gcc/gcc-4.9/libgfortran/intrinsics/cshift0.c:131:5: error: previously used here
     case GFC_DTYPE_REAL_8:
     ^
/toolchain/build/../gcc/gcc-4.9/libgfortran/intrinsics/cshift0.c:180:5: error: duplicate case value
     case GFC_DTYPE_COMPLEX_16:
     ^
/toolchain/build/../gcc/gcc-4.9/libgfortran/intrinsics/cshift0.c:161:5: error: previously used here
     case GFC_DTYPE_COMPLEX_8:
     ^
```
