### ISSUE TITLE
Beyond the NDK

### ISSUE THREAD

**Issue by ghost** [buffer51/android-gfortran#7]
This isn't really an issue, but I didn't know how else to ask a question, and provide feedback (the feedback is really just : "This is awesome!!!").

I had been waiting for something like this project for over a year. I didn't have the time to figure out how to build newer versions of the NDK past r8 that was figured out a few years ago, and this really saved me. I really appreciate it! I now have gfortran for every possible system that the NDK supports, and I've confirmed that it works on multiple android devices and both the x86 and x86_64 emulator.

I wonder if you or anyone else has taken a stab at getting support for fortran in the CrystaX NDK. I think since google has abandoned anyone who wants to use gcc, it seems like CrystaX is going to be the best/only solution. I think with what you have provided here, it might be as simple as looking at the CrystaX build of the NDK.

**Comment by buffer51** [comment]
Hi @nuclearlee,

Thanks for the feedback, I'm glad it is of use to you!

I recently read about the release of NDK r13b (I'm updating this repo as we speak) and the deprecation of GCC... I haven't thought about contributing CrystaX NDK ; when I started this project it was because I wanted to keep using the regular up-to-date NDK and not a modified version. I'm not sure CrystaX is still very active, but I'll reach out. Like you said, in the end they might be the only one left to support GCC.
