### ISSUE TITLE
fortran etime

### ISSUE THREAD

**Issue by nmnobre** [buffer51/android-gfortran#9]
Hi,

I'm trying to build an old application which requires etime. I'm trying to compile it like this:

/opt/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gfortran -O2 -std=f95 vec.f --sysroot=$(ANDROID_NDK)/platforms/android-24/arch-arm64/

The resulting error is:

/tmp/ccG2hvrY.o: In function `MAIN__':
vec.f:(.text+0xf0): undefined reference to `etime_'
vec.f:(.text+0x164): undefined reference to `etime_'
collect2: error: ld returned 1 exit status

Any ideas?

**Comment by buffer51** [comment]
Hi @nmnobre,

Is the code available somewhere to take a look? Without more information, I recommend two things:
- Using a standalone toolchain rather than setting the sysroot yourself (it does that and more things that can help linking, see [this](https://github.com/buffer51/android-gfortran#deploying)).
- Since `etime_` should be in libgfortran, try adding it explicitely with the `-lgfortran` flag.

**Comment by nmnobre** [comment]
Hi @buffer51,

It turns out etime is a GNU extension and, as such, I cannot force strict standard compliance. Removing -std=f95 solves the issue. My bad.

Can you elaborate on the standalone toolchain recommendation? What I did was download the latest prebuilt standalone toolchain for aarch64 (linux-x86_64 host) that you provide and then replaced the respective toolchain on Google's (prebuilt) Android NDK with this version. I could not figure out how to use ndk-build that's why I'm invoking and linking everything by hand.

**Comment by buffer51** [comment]
@nmnobre Glad you fixed it.

Regarding the standalone toolchain: if you are using `ndk-build`, what you did is fine, because `ndk-build` is essentially a script to set all include/lib paths. But if you're not, to be sure not to mess it up, the NDK provides a script to export the toolchain as a standalone toolchain (see the very last paragraph of my README). You'll end up with a toolchain that has all those paths set correctly, which can solve some missing includes/references.

What you want to do is exactly what you did (download, replace the prebuilt inside the NDK) then call that script with the Android API level you want, the STL you want, etc. You can refer to [this](https://developer.android.com/ndk/guides/standalone_toolchain.html). It will create a folder with the standalone toolchain, which you can then use like you did without worrying about the sysroot & al.
